 name: Update alerts
 on:
   push:
     push:
   schedule:
     - cron: "0 * * * *"
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: "Check out this repo"
         uses: actions/checkout@v4
 
       - name: Checkout Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.x'
           cache: 'pip'
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
       - name: Run script
         run: python county_results.py

       - name: Run script
         run: python cong_results.py

       - name: "Commit and push if it changed"
         run: |-
             git config user.name "Automated"
             git config user.email "actions@users.noreply.github.com"
             git add -A
             timestamp=$(date -u)
             git commit -m "Latest data: ${timestamp}" || exit 0
             git push
